# ====================
# Module configuration
# ====================

# Enable or disable some of the integrated modules on start
EnableModules:
    CustomItemManager: true
    MapDisplayManager: true

# Configuration for MapDisplayManager
MapDisplayManager:
    # If true MapDisplayManager will try to read map displays from the world data file
    # If disabled map displays wont be persitent between restarts
    EnableWorldDataLoading: true
    
    # If true map displays wont be saved to the world file
    DisableWorldDataSaving: false

# =============================
# Library Loading Configuration
# =============================
LibrarySettings:
   # Can be used to set a diffrent library folder than /plugins/NovaCore/Lib. Leave empty for default path
   LibraryDirectoryOverride: ""
   
   # If a library is set to true here the library loader will not attempt to load it even it even if it detects that the library does not exist
   BlockedLibraries:
      examination-api-1.3.1-SNAPSHOT: false
      adventure-api-4.14.0: false
   
   # Set to true to not shutdown if a library fails to load
   DoNotShutdownOnFail: false
   
   # Set to true to get extra debug messages
   Verbose: false

# =====================
# Logging and Debugging
# =====================

# Values are: NONE, TRACE, DEBUG, INFO, WARN, ERROR and FATAL
# If set to NONE the plugin wont attempt to change the log level of op players
# This is applied before the permission based log level so the permission based log level will have higher priority than the op one
# To not spam the chat op players this should never be set to anything lower than INFO unless you are trying to debug things
DefaultOpLogLevel: "ERROR"

# Disable the built in log level colors
DisableBuiltInLogColors: false

# Enable to show more debug messages
ExtendedDebugging: false

# Enable this to allow this plugin to run on unsupported versions of spigot. This will disable all version independant usils and nms features 
# Only enable this if you know what you are doing
IgnoreMissingNMS: false

# ===================
# Multiverse Settings
# ===================
Multiverse:
    # Put the names of worlds in this list to load them on start
    AutoLoadWorlds: []

# ==============================
# Third party web based services
# ==============================
WebServices:
    # The custom hastebin server to use for debugging and for the built in hastebin implementation. Note that this only affects the hastebin instace from NovaCore#getHastebinInstance() and NovaCommons
    # To self host this see https://hub.docker.com/r/rlister/hastebin or https://github.com/toptal/haste-server
    Hastebin:
        URL: "https://hastebin.novauniverse.net"
        UserAgent: "NovaCore 2.0.0 Hastebin Java Api"
        Timeout: 10000
    # Settings for the mojang api proxy
    # If you want to self host this check out https://github.com/NovaUniverse/MojangAPIProxy
    # You can also set it up as a docker container using
    # docker run --restart=unless-stopped --name mojangapiproxy -d -p 80:80 novauniverse/mojangapiproxy
    MojangAPIProxy:    
        URL: "https://mojangapi.novauniverse.net/"
        UserAgent: "NovaCore 2.0.0"
        Timeout: 10000
    # Map display web request settings
    MapDisplays:
        Disable: false
        # If images are not loading you can try to geneare a user agent here https://user-agents.net/random and put it in the field below
        UserAgent: "NovaCore 2.0.0 MapImageDisplays"
        Timeout: 10000

# ================================
# AdvancedGUI + Multiverse support
# ================================

# By default the MultiverseManager will try to reload AdvancedGUIs if it detects the plugin
# To disable this set the following value to true
DisableAdvancedGUIAupport: false
AdvancedGUIMultiverseReloadDelay: 20

# ==============
# Plugin metrics
# ==============

# Set to true to disable bStats
DisableMetrics: false

# ===========================
# Command registrator options
# ===========================

# Change how the command registrator behaves. We recommand that you dont change these settings unless you know what you are doing
CommandRegistrator:
    # Disable the unregistration of commands when plugins are disabled
    DisableUnregistation: false
    ForceUseReflectionBasedRegistrator: false

# ==========================================
# Expiremental / Potentially laggy functions
# ==========================================

# By default the packet manager is turned off until another plugin calls NovaCore#enablePacketManager()
# By setting this to true the packet manager will be enabled on start
EnablePacketManager: false