# Enable or disable some of the integrated modules on start
EnableModules:
    CustomItemManager: true
    MapDisplayManager: true

# Configuration for MapDisplayManager
MapDisplayManager:
    # If true MapDisplayManager will try to read map displays from the world data file
    # If disabled map displays wont be persitent between restarts
    EnableWorldDataLoading: true
    
    # If true map displays wont be saved to the world file
    DisableWorldDataSaving: false

# Values are: NONE, TRACE, DEBUG, INFO, WARN, ERROR and FATAL
# If set to NONE the plugin wont attempt to change the log level of op players
# This is applied before the permission based log level so the permission based log level will have higher priority than the op one
# To not spam the chat op players this should never be set to anything lower than INFO unless you are trying to debug things
DefaultOpLogLevel: "ERROR"

# Enable to show more debug messages
ExtendedDebugging: false

# Enable this to allow this plugin to run on unsupported versions of spigot. This will disable all version independant usils and nms features 
# Only enable this if you know what you are doing
IgnoreMissingNMS: false

# Set to true to disable bStats
DisableMetrics: false

# The url of the mojang api proxy to use
# If you want to self host this check out https://github.com/NovaUniverse/MojangAPIProxy
# You can also set it up as a docker container using
# docker run --restart=unless-stopped --name mojangapiproxy -d -p 80:80 novauniverse/mojangapiproxy
MojangAPIProxyURL: "https://mojangapi.novauniverse.net/"

# The custom hastebin server to use for debugging and for the built in hastebin implementation. Note that this only affects the hastebin instace from NovaCore#getHastebinInstance() and NovaCommons
# To self host this see https://hub.docker.com/r/rlister/hastebin or https://github.com/toptal/haste-server
HastebinURL: "https://hastebin.novauniverse.net"

# By default the MultiverseManager will try to reload AdvancedGUIs if it detects the plugin
# To disable this set the following value to true
DisableAdvancedGUIAupport: false
AdvancedGUIMultiverseReloadDelay: 20

# By default the packet manager is turned off until another plugin calls NovaCore#enablePacketManager()
# By setting this to true the packet manager will be enabled on start
EnablePacketManager: false